AllCops:
  Exclude:
    - bin/*
    - config/application.rb
    - config/environments/*.rb
    - config/initializers/*.rb
    - config/puma.rb
    - config/spring.rb
    - db/schema.rb
    - db/migrate/20170401213413_devise_token_auth_create_users.rb
    - spec/rails_helper.rb
    - spec/spec_helper.rb

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false
