# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06b3e9b58142c38eff26a7a6c01388afc756789a4078e3a5a74ec1fdc4fe4c10a184b159e978be513c1bbcd2003d0ec350fb518221d7a3971d67f258115328d0

test:
  secret_key_base: 77103c7c4a6b59ca48964647a4ceaf8366933f5b2e253980e22247b0bc4479b2d19167159cdb2108f3058e2f959cc8bd52e67aadcbdb4f6949d62104240351b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
